app:
  api-key: ${SAMPLEAPI_API_KEY}
  base-uri: http://localhost:8080

micronaut:
  application:
    name: micronaut-sample
  server:
    netty:
      worker:
        threads: 10
        childOptions:
          autoRead: false
          autoClose: true
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
    url:
      enabled: true
    prometheus:
      sensitive: false

jackson:
  property-naming-strategy: SNAKE_CASE
  serialization:
    write-dates-as-timestamps: false