package dev.danielpadua.micronautexampleapi.contracts;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.ZonedDateTime;

@Schema(name = "ErrorContract", description = "Error contract for the micronaut example api")
public class ErrorContract {
    private ZonedDateTime timestamp;
    private String code;
    private String message;

    public ErrorContract() { }

    public ErrorContract(ZonedDateTime timestamp, String code, String message) {
        this.timestamp = timestamp;
        this.code = code;
        this.message = message;
    }

    @Schema(description = "Error timestamp generated by micronaut example api server")
    public ZonedDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(ZonedDateTime timestamp) {
        this.timestamp = timestamp;
    }

    @Schema(description = "Micronaut example api internal error code")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Schema(description = "Error description")
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}
